info:
  component: Discovery Server
  instance-id: ${spring.application.name}:${spring.application.instance_id:${spring.cloud.client.ip-address}}:${server.port}
server:
  port: 8761
  tomcat:
    max-connections: 1024    
    threads:
      min-spare: 1
      max: 25
management.server.port: 8081
spring:
  application:
    name: discovery-service
  main:
    banner-mode: off

eureka:
  server:
    enable-self-preservation: true
    expected-client-renewal-interval-seconds: 10
  instance:
    hostname: localhost
    instance-id: ${info.instance-id}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 15
  client:
    enabled: true
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    enabled-by-default: true
    web.exposure.include: "*"
  endpoint:
    info.enabled: true
    metrics.enabled: true
    shutdown.enabled: true
    health:
      enabled: true
      probes.enabled: true
      show-details: always
  metrics:
    enable:
      all: true
    export:
      atlas.enabled: false

logging:
  level:
    root: INFO
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN
    c.n.e.registry.AbstractInstanceRegistry: ERROR # ignore WARN No remote registry available for the remote region us-east-1
